language: objective-c

osx_image: xcode8.2

install:
  - mkdir -p /Users/travis/build/facebook/.nvm
  - export NVM_DIR="/Users/travis/build/facebook/.nvm"
  - brew install nvm
  - source $(brew --prefix nvm)/nvm.sh
  # TODO npm 2 started stalling on Travis, t11852928
  - nvm install 5
  - wget https://github.com/yarnpkg/yarn/releases/download/v0.16.0/yarn-0.16.0.js
  - export yarn="node $(pwd)/yarn-0.16.0.js"
  - $yarn install
  - cd example && $yarn install && cd ..

script:
  - if [[ "$TEST_TYPE" = objc-ios ]]; then xcodebuild test -workspace ios/RNPhotosFramework.xcworkspace -scheme RNPhotosFramework -destination 'platform=iOS Simulator,name=iPhone 5s'; fi
  - if [[ "$TEST_TYPE" = js ]]; then npm test -- --maxWorkers=1; fi

env:
  matrix:
    - TEST_TYPE=objc-ios
    - TEST_TYPE=js

branches:
  only:
    - master
    - /^.*-stable$/

notifications:
  email:
    recipients:
      - olof.dahlbom@me.com
    on_failure: change
    on_success: change
